language: ruby
sudo: false
cache: bundler

rvm:
  - 2.1
  - 2.2
  - jruby
  - rbx-2

gemfile:
  - gemfiles/active_record_4.1.gemfile
  - gemfiles/active_record_4.2.gemfile

matrix:
  include:
    - gemfile: gemfiles/active_record_edge.gemfile
      rvm: 2.2
  allow_failures:
    - rvm: jruby
    - rvm: rbx-2
    - gemfile: gemfiles/active_record_edge.gemfile
      rvm: 2.2

